### ISSUE TITLE
ExTypesense.Connection.new doesn't work with MIX_ENV=test

### ISSUE THREAD

**Issue by rodesousa** [jaeyson/ex_typesense#26]
elixir version: 1.15.4
ex_typesense version: 0.4

I configure ex typesense into runtime.exs. But when I run test all of data from ExTypesense.Connection.new is nil
I put the configuration into test.exs but no effect

![Screenshot from 2024-06-24 15-29-49](https://github.com/jaeyson/ex_typesense/assets/8577532/40112997-fdd3-4e40-a249-883549d1b7fa)
![Screenshot from 2024-06-24 15-30-25](https://github.com/jaeyson/ex_typesense/assets/8577532/ce2dad33-21b8-42a2-8134-4676eb9b0110)

**Comment by jaeyson** [comment]
Hi @rodesousa :wave:

I missed that part. Thanks for letting me know!

**Comment by jaeyson** [comment]
@rodesousa can you try add this in `config/test.exs`?

```elixir
config :ex_typesense,
  api_key: "xyz",
  host: "localhost",
  port: 8108,
  scheme: "http"
```

**Comment by jaeyson** [comment]
@rodesousa kindly check this PR #30. Let me know if this fixes your issue.

### Problem

Setting the credentials dynamically won't work since the `Connection` module by default is a struct (hence, compile time).

This also affects the test files, since it relies on explicit connection string. Leaving it blank will throw an error.

To reproduce:

1. open shell in `test` env: `MIX_ENV=test iex -S mix`
2. put env in application:
```elixir
Application.put_all_env(
  ex_typesense: [
    api_key: "xyz",
    host: "localhost",
    port: 8108,
    scheme: "http"
  ]
)
```
3. run `ExTypesense.Connection.new`
4. The `Connection` struct field values returns `nil`.

### Workaround

Since the problem came from making the connection a struct, it defeats the purpose of making it dynamic (runtime). So we have to change it from struct to map.

**Comment by rodesousa** [comment]
@jaeyson It works ! :)
